name = "quilometragem"
compatibility_date = "2024-10-01"

# Diga ao Pages onde estão os arquivos estáticos do seu site.
# Ajuste se seu index.html estiver em outra pasta.
pages_build_output_dir = "site"

[[d1_databases]]
binding = "DB"
database_name = "quilometragem-db"
database_id = "fdbae221-2b15-4e3a-b2ae-627faa32a4d5"