name = "quilometragem"
compatibility_date = "2024-10-01"

[[d1_databases]]
binding = "DB"
database_name = "quilometragem-db"     # coloque aqui o nome retornado no 'wrangler d1 create'
database_id = "SEU_DATABASE_ID_AQUI"   # coloque aqui o ID retornado